// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct __darwin_arm_thread_state64 {
 *     __uint64_t __x[29];
 *     __uint64_t __fp;
 *     __uint64_t __lr;
 *     __uint64_t __sp;
 *     __uint64_t __pc;
 *     __uint32_t __cpsr;
 *     __uint32_t __pad;
 * } arm_thread_state64_t
 * }
 */
public class arm_thread_state64_t extends __darwin_arm_thread_state64 {

    arm_thread_state64_t() {
        // Should not be called directly
    }
}

