// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct __arm_pagein_state {
 *     int __pagein_error;
 * } arm_pagein_state_t
 * }
 */
public class arm_pagein_state_t extends __arm_pagein_state {

    arm_pagein_state_t() {
        // Should not be called directly
    }
}

