// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct __darwin_arm_neon_state64 {
 *     __uint128_t __v[32];
 *     __uint32_t __fpsr;
 *     __uint32_t __fpcr;
 * } arm_neon_state64_t
 * }
 */
public class arm_neon_state64_t extends __darwin_arm_neon_state64 {

    arm_neon_state64_t() {
        // Should not be called directly
    }
}

