// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct __darwin_arm_exception_state {
 *     __uint32_t __exception;
 *     __uint32_t __fsr;
 *     __uint32_t __far;
 * } arm_exception_state_t
 * }
 */
public class arm_exception_state_t extends __darwin_arm_exception_state {

    arm_exception_state_t() {
        // Should not be called directly
    }
}

