// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct host_preferred_user_arch {
 *     cpu_type_t cpu_type;
 *     cpu_subtype_t cpu_subtype;
 * }
 * }
 */
public class host_preferred_user_arch {

    host_preferred_user_arch() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.C_INT.withName("cpu_type"),
        ObjCRuntime.C_INT.withName("cpu_subtype")
    ).withName("host_preferred_user_arch");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt cpu_type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("cpu_type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cpu_type_t cpu_type
     * }
     */
    public static final OfInt cpu_type$layout() {
        return cpu_type$LAYOUT;
    }

    private static final long cpu_type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cpu_type_t cpu_type
     * }
     */
    public static final long cpu_type$offset() {
        return cpu_type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cpu_type_t cpu_type
     * }
     */
    public static int cpu_type(MemorySegment struct) {
        return struct.get(cpu_type$LAYOUT, cpu_type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cpu_type_t cpu_type
     * }
     */
    public static void cpu_type(MemorySegment struct, int fieldValue) {
        struct.set(cpu_type$LAYOUT, cpu_type$OFFSET, fieldValue);
    }

    private static final OfInt cpu_subtype$LAYOUT = (OfInt)$LAYOUT.select(groupElement("cpu_subtype"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * cpu_subtype_t cpu_subtype
     * }
     */
    public static final OfInt cpu_subtype$layout() {
        return cpu_subtype$LAYOUT;
    }

    private static final long cpu_subtype$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * cpu_subtype_t cpu_subtype
     * }
     */
    public static final long cpu_subtype$offset() {
        return cpu_subtype$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * cpu_subtype_t cpu_subtype
     * }
     */
    public static int cpu_subtype(MemorySegment struct) {
        return struct.get(cpu_subtype$LAYOUT, cpu_subtype$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * cpu_subtype_t cpu_subtype
     * }
     */
    public static void cpu_subtype(MemorySegment struct, int fieldValue) {
        struct.set(cpu_subtype$LAYOUT, cpu_subtype$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

