// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct host_can_has_debugger_info {
 *     boolean_t can_has_debugger;
 * } host_can_has_debugger_info_data_t
 * }
 */
public class host_can_has_debugger_info_data_t extends host_can_has_debugger_info {

    host_can_has_debugger_info_data_t() {
        // Should not be called directly
    }
}

