// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct host_sched_info {
 *     integer_t min_timeout;
 *     integer_t min_quantum;
 * } host_sched_info_data_t
 * }
 */
public class host_sched_info_data_t extends host_sched_info {

    host_sched_info_data_t() {
        // Should not be called directly
    }
}

