// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct host_basic_info {
 *     integer_t max_cpus;
 *     integer_t avail_cpus;
 *     natural_t memory_size;
 *     cpu_type_t cpu_type;
 *     cpu_subtype_t cpu_subtype;
 *     cpu_threadtype_t cpu_threadtype;
 *     integer_t physical_cpu;
 *     integer_t physical_cpu_max;
 *     integer_t logical_cpu;
 *     integer_t logical_cpu_max;
 *     uint64_t max_mem;
 * } host_basic_info_data_t
 * }
 */
public class host_basic_info_data_t extends host_basic_info {

    host_basic_info_data_t() {
        // Should not be called directly
    }
}

