// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef mach_vm_range_recipe_v1_t mach_vm_range_recipe_t
 * }
 */
public class mach_vm_range_recipe_t extends mach_vm_range_recipe_v1_t {

    mach_vm_range_recipe_t() {
        // Should not be called directly
    }
}

