// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct mach_port_info_ext {
 *     mach_port_status_t mpie_status;
 *     mach_port_msgcount_t mpie_boost_cnt;
 *     uint32_t reserved[6];
 * } mach_port_info_ext_t
 * }
 */
public class mach_port_info_ext_t extends mach_port_info_ext {

    mach_port_info_ext_t() {
        // Should not be called directly
    }
}

