// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef mach_msg_security_trailer_t mach_msg_format_0_trailer_t
 * }
 */
public class mach_msg_format_0_trailer_t extends mach_msg_security_trailer_t {

    mach_msg_format_0_trailer_t() {
        // Should not be called directly
    }
}

