// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct mach_task_basic_info {
 *     mach_vm_size_t virtual_size;
 *     mach_vm_size_t resident_size;
 *     mach_vm_size_t resident_size_max;
 *     time_value_t user_time;
 *     time_value_t system_time;
 *     policy_t policy;
 *     integer_t suspend_count;
 * } mach_task_basic_info_data_t
 * }
 */
public class mach_task_basic_info_data_t extends mach_task_basic_info {

    mach_task_basic_info_data_t() {
        // Should not be called directly
    }
}

