// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct _malloc_zone_t malloc_zone_t
 * }
 */
public class malloc_zone_t extends _malloc_zone_t {

    malloc_zone_t() {
        // Should not be called directly
    }
}

