// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef kern_return_t (memory_reader_t)(task_t, vm_address_t, vm_size_t, void **)
 * }
 */
public class memory_reader_t {

    memory_reader_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(int remote_task, long remote_address, long size, MemorySegment local_memory);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        ObjCRuntime.C_INT,
        ObjCRuntime.C_INT,
        ObjCRuntime.C_LONG,
        ObjCRuntime.C_LONG,
        ObjCRuntime.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = ObjCRuntime.upcallHandle(memory_reader_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(memory_reader_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,int remote_task, long remote_address, long size, MemorySegment local_memory) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, remote_task, remote_address, size, local_memory);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

