// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct memory_object_attr_info {
 *     memory_object_copy_strategy_t copy_strategy;
 *     memory_object_cluster_size_t cluster_size;
 *     boolean_t may_cache_object;
 *     boolean_t temporary;
 * } memory_object_attr_info_data_t
 * }
 */
public class memory_object_attr_info_data_t extends memory_object_attr_info {

    memory_object_attr_info_data_t() {
        // Should not be called directly
    }
}

