// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct objc_object {
 *     OBJC_ISA_AVAILABILITY Class isa;
 * }
 * }
 */
public class objc_object {

    objc_object() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.C_POINTER.withName("isa")
    ).withName("objc_object");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout isa$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("isa"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * OBJC_ISA_AVAILABILITY Class isa
     * }
     */
    public static final AddressLayout isa$layout() {
        return isa$LAYOUT;
    }

    private static final long isa$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * OBJC_ISA_AVAILABILITY Class isa
     * }
     */
    public static final long isa$offset() {
        return isa$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * OBJC_ISA_AVAILABILITY Class isa
     * }
     */
    public static MemorySegment isa(MemorySegment struct) {
        return struct.get(isa$LAYOUT, isa$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * OBJC_ISA_AVAILABILITY Class isa
     * }
     */
    public static void isa(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(isa$LAYOUT, isa$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

