// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct {
 *     void *opaque1;
 *     long opaque2;
 * }
 * }
 */
public class OSQueueHead {

    OSQueueHead() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.C_POINTER.withName("opaque1"),
        ObjCRuntime.C_LONG.withName("opaque2")
    ).withName("$anon$48:18");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout opaque1$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("opaque1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * void *opaque1
     * }
     */
    public static final AddressLayout opaque1$layout() {
        return opaque1$LAYOUT;
    }

    private static final long opaque1$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * void *opaque1
     * }
     */
    public static final long opaque1$offset() {
        return opaque1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * void *opaque1
     * }
     */
    public static MemorySegment opaque1(MemorySegment struct) {
        return struct.get(opaque1$LAYOUT, opaque1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * void *opaque1
     * }
     */
    public static void opaque1(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(opaque1$LAYOUT, opaque1$OFFSET, fieldValue);
    }

    private static final OfLong opaque2$LAYOUT = (OfLong)$LAYOUT.select(groupElement("opaque2"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * long opaque2
     * }
     */
    public static final OfLong opaque2$layout() {
        return opaque2$LAYOUT;
    }

    private static final long opaque2$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * long opaque2
     * }
     */
    public static final long opaque2$offset() {
        return opaque2$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * long opaque2
     * }
     */
    public static long opaque2(MemorySegment struct) {
        return struct.get(opaque2$LAYOUT, opaque2$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * long opaque2
     * }
     */
    public static void opaque2(MemorySegment struct, long fieldValue) {
        struct.set(opaque2$LAYOUT, opaque2$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

