// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct policy_timeshare_limit {
 *     integer_t max_priority;
 * } policy_timeshare_limit_data_t
 * }
 */
public class policy_timeshare_limit_data_t extends policy_timeshare_limit {

    policy_timeshare_limit_data_t() {
        // Should not be called directly
    }
}

