// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct policy_infos {
 *     policy_timeshare_info_data_t ts;
 *     policy_rr_info_data_t rr;
 *     policy_fifo_info_data_t fifo;
 * } policy_info_data_t
 * }
 */
public class policy_info_data_t extends policy_infos {

    policy_info_data_t() {
        // Should not be called directly
    }
}

