// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct policy_timeshare_base {
 *     integer_t base_priority;
 * }
 * }
 */
public class policy_timeshare_base {

    policy_timeshare_base() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.C_INT.withName("base_priority")
    ).withName("policy_timeshare_base");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt base_priority$LAYOUT = (OfInt)$LAYOUT.select(groupElement("base_priority"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * integer_t base_priority
     * }
     */
    public static final OfInt base_priority$layout() {
        return base_priority$LAYOUT;
    }

    private static final long base_priority$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * integer_t base_priority
     * }
     */
    public static final long base_priority$offset() {
        return base_priority$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * integer_t base_priority
     * }
     */
    public static int base_priority(MemorySegment struct) {
        return struct.get(base_priority$LAYOUT, base_priority$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * integer_t base_priority
     * }
     */
    public static void base_priority(MemorySegment struct, int fieldValue) {
        struct.set(base_priority$LAYOUT, base_priority$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

