// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct processor_set_basic_info {
 *     int processor_count;
 *     int default_policy;
 * } processor_set_basic_info_data_t
 * }
 */
public class processor_set_basic_info_data_t extends processor_set_basic_info {

    processor_set_basic_info_data_t() {
        // Should not be called directly
    }
}

