// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct processor_basic_info {
 *     cpu_type_t cpu_type;
 *     cpu_subtype_t cpu_subtype;
 *     boolean_t running;
 *     int slot_num;
 *     union {
 *         boolean_t is_master;
 *         boolean_t is_main;
 *     };
 * } processor_basic_info_data_t
 * }
 */
public class processor_basic_info_data_t extends processor_basic_info {

    processor_basic_info_data_t() {
        // Should not be called directly
    }
}

