// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct task_affinity_tag_info {
 *     integer_t set_count;
 *     integer_t min;
 *     integer_t max;
 *     integer_t task_count;
 * } task_affinity_tag_info_data_t
 * }
 */
public class task_affinity_tag_info_data_t extends task_affinity_tag_info {

    task_affinity_tag_info_data_t() {
        // Should not be called directly
    }
}

