// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct task_basic_info_64_2 {
 *     integer_t suspend_count;
 *     mach_vm_size_t virtual_size;
 *     mach_vm_size_t resident_size;
 *     time_value_t user_time;
 *     time_value_t system_time;
 *     policy_t policy;
 * } task_basic_info_64_2_data_t
 * }
 */
public class task_basic_info_64_2_data_t extends task_basic_info_64_2 {

    task_basic_info_64_2_data_t() {
        // Should not be called directly
    }
}

