// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct task_kernelmemory_info {
 *     uint64_t total_palloc;
 *     uint64_t total_pfree;
 *     uint64_t total_salloc;
 *     uint64_t total_sfree;
 * } task_kernelmemory_info_data_t
 * }
 */
public class task_kernelmemory_info_data_t extends task_kernelmemory_info {

    task_kernelmemory_info_data_t() {
        // Should not be called directly
    }
}

