// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct task_inspect_basic_counts {
 *     uint64_t instructions;
 *     uint64_t cycles;
 * } task_inspect_basic_counts_data_t
 * }
 */
public class task_inspect_basic_counts_data_t extends task_inspect_basic_counts {

    task_inspect_basic_counts_data_t() {
        // Should not be called directly
    }
}

