// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct task_trace_memory_info {
 *     uint64_t user_memory_address;
 *     uint64_t buffer_size;
 *     uint64_t mailbox_array_size;
 * }
 * }
 */
public class task_trace_memory_info {

    task_trace_memory_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.align(ObjCRuntime.C_LONG_LONG, 4).withName("user_memory_address"),
        ObjCRuntime.align(ObjCRuntime.C_LONG_LONG, 4).withName("buffer_size"),
        ObjCRuntime.align(ObjCRuntime.C_LONG_LONG, 4).withName("mailbox_array_size")
    ).withName("task_trace_memory_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong user_memory_address$LAYOUT = (OfLong)$LAYOUT.select(groupElement("user_memory_address"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t user_memory_address
     * }
     */
    public static final OfLong user_memory_address$layout() {
        return user_memory_address$LAYOUT;
    }

    private static final long user_memory_address$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t user_memory_address
     * }
     */
    public static final long user_memory_address$offset() {
        return user_memory_address$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t user_memory_address
     * }
     */
    public static long user_memory_address(MemorySegment struct) {
        return struct.get(user_memory_address$LAYOUT, user_memory_address$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t user_memory_address
     * }
     */
    public static void user_memory_address(MemorySegment struct, long fieldValue) {
        struct.set(user_memory_address$LAYOUT, user_memory_address$OFFSET, fieldValue);
    }

    private static final OfLong buffer_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("buffer_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t buffer_size
     * }
     */
    public static final OfLong buffer_size$layout() {
        return buffer_size$LAYOUT;
    }

    private static final long buffer_size$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t buffer_size
     * }
     */
    public static final long buffer_size$offset() {
        return buffer_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t buffer_size
     * }
     */
    public static long buffer_size(MemorySegment struct) {
        return struct.get(buffer_size$LAYOUT, buffer_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t buffer_size
     * }
     */
    public static void buffer_size(MemorySegment struct, long fieldValue) {
        struct.set(buffer_size$LAYOUT, buffer_size$OFFSET, fieldValue);
    }

    private static final OfLong mailbox_array_size$LAYOUT = (OfLong)$LAYOUT.select(groupElement("mailbox_array_size"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t mailbox_array_size
     * }
     */
    public static final OfLong mailbox_array_size$layout() {
        return mailbox_array_size$LAYOUT;
    }

    private static final long mailbox_array_size$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t mailbox_array_size
     * }
     */
    public static final long mailbox_array_size$offset() {
        return mailbox_array_size$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t mailbox_array_size
     * }
     */
    public static long mailbox_array_size(MemorySegment struct) {
        return struct.get(mailbox_array_size$LAYOUT, mailbox_array_size$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t mailbox_array_size
     * }
     */
    public static void mailbox_array_size(MemorySegment struct, long fieldValue) {
        struct.set(mailbox_array_size$LAYOUT, mailbox_array_size$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

