// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct thread_identifier_info {
 *     uint64_t thread_id;
 *     uint64_t thread_handle;
 *     uint64_t dispatch_qaddr;
 * }
 * }
 */
public class thread_identifier_info {

    thread_identifier_info() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        ObjCRuntime.C_LONG_LONG.withName("thread_id"),
        ObjCRuntime.C_LONG_LONG.withName("thread_handle"),
        ObjCRuntime.C_LONG_LONG.withName("dispatch_qaddr")
    ).withName("thread_identifier_info");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong thread_id$LAYOUT = (OfLong)$LAYOUT.select(groupElement("thread_id"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t thread_id
     * }
     */
    public static final OfLong thread_id$layout() {
        return thread_id$LAYOUT;
    }

    private static final long thread_id$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t thread_id
     * }
     */
    public static final long thread_id$offset() {
        return thread_id$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t thread_id
     * }
     */
    public static long thread_id(MemorySegment struct) {
        return struct.get(thread_id$LAYOUT, thread_id$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t thread_id
     * }
     */
    public static void thread_id(MemorySegment struct, long fieldValue) {
        struct.set(thread_id$LAYOUT, thread_id$OFFSET, fieldValue);
    }

    private static final OfLong thread_handle$LAYOUT = (OfLong)$LAYOUT.select(groupElement("thread_handle"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t thread_handle
     * }
     */
    public static final OfLong thread_handle$layout() {
        return thread_handle$LAYOUT;
    }

    private static final long thread_handle$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t thread_handle
     * }
     */
    public static final long thread_handle$offset() {
        return thread_handle$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t thread_handle
     * }
     */
    public static long thread_handle(MemorySegment struct) {
        return struct.get(thread_handle$LAYOUT, thread_handle$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t thread_handle
     * }
     */
    public static void thread_handle(MemorySegment struct, long fieldValue) {
        struct.set(thread_handle$LAYOUT, thread_handle$OFFSET, fieldValue);
    }

    private static final OfLong dispatch_qaddr$LAYOUT = (OfLong)$LAYOUT.select(groupElement("dispatch_qaddr"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint64_t dispatch_qaddr
     * }
     */
    public static final OfLong dispatch_qaddr$layout() {
        return dispatch_qaddr$LAYOUT;
    }

    private static final long dispatch_qaddr$OFFSET = 16;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint64_t dispatch_qaddr
     * }
     */
    public static final long dispatch_qaddr$offset() {
        return dispatch_qaddr$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint64_t dispatch_qaddr
     * }
     */
    public static long dispatch_qaddr(MemorySegment struct) {
        return struct.get(dispatch_qaddr$LAYOUT, dispatch_qaddr$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint64_t dispatch_qaddr
     * }
     */
    public static void dispatch_qaddr(MemorySegment struct, long fieldValue) {
        struct.set(dispatch_qaddr$LAYOUT, dispatch_qaddr$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

