// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vm_extmod_statistics {
 *     int64_t task_for_pid_count;
 *     int64_t task_for_pid_caller_count;
 *     int64_t thread_creation_count;
 *     int64_t thread_creation_caller_count;
 *     int64_t thread_set_state_count;
 *     int64_t thread_set_state_caller_count;
 * } vm_extmod_statistics_data_t
 * }
 */
public class vm_extmod_statistics_data_t extends vm_extmod_statistics {

    vm_extmod_statistics_data_t() {
        // Should not be called directly
    }
}

