// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vm_purgeable_stat {
 *     uint64_t count;
 *     uint64_t size;
 * } vm_purgeable_stat_t
 * }
 */
public class vm_purgeable_stat_t extends vm_purgeable_stat {

    vm_purgeable_stat_t() {
        // Should not be called directly
    }
}

