// Generated by jextract

package com.github.marschall.objectivej.header;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct vm_statistics64 {
 *     natural_t free_count;
 *     natural_t active_count;
 *     natural_t inactive_count;
 *     natural_t wire_count;
 *     uint64_t zero_fill_count;
 *     uint64_t reactivations;
 *     uint64_t pageins;
 *     uint64_t pageouts;
 *     uint64_t faults;
 *     uint64_t cow_faults;
 *     uint64_t lookups;
 *     uint64_t hits;
 *     uint64_t purges;
 *     natural_t purgeable_count;
 *     natural_t speculative_count;
 *     uint64_t decompressions;
 *     uint64_t compressions;
 *     uint64_t swapins;
 *     uint64_t swapouts;
 *     natural_t compressor_page_count;
 *     natural_t throttled_count;
 *     natural_t external_page_count;
 *     natural_t internal_page_count;
 *     uint64_t total_uncompressed_pages_in_compressor;
 * } vm_statistics64_data_t
 * }
 */
public class vm_statistics64_data_t extends vm_statistics64 {

    vm_statistics64_data_t() {
        // Should not be called directly
    }
}

